// Code generated by protoc-gen-go. DO NOT EDIT.
// source: backup.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BackupEntry struct {
	Op                   Operation `protobuf:"varint,1,opt,name=op,proto3,enum=kv.proto.Operation" json:"op,omitempty"`
	Key                  string    `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value                string    `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *BackupEntry) Reset()         { *m = BackupEntry{} }
func (m *BackupEntry) String() string { return proto.CompactTextString(m) }
func (*BackupEntry) ProtoMessage()    {}
func (*BackupEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_65240d19de191688, []int{0}
}

func (m *BackupEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BackupEntry.Unmarshal(m, b)
}
func (m *BackupEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BackupEntry.Marshal(b, m, deterministic)
}
func (m *BackupEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BackupEntry.Merge(m, src)
}
func (m *BackupEntry) XXX_Size() int {
	return xxx_messageInfo_BackupEntry.Size(m)
}
func (m *BackupEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_BackupEntry.DiscardUnknown(m)
}

var xxx_messageInfo_BackupEntry proto.InternalMessageInfo

func (m *BackupEntry) GetOp() Operation {
	if m != nil {
		return m.Op
	}
	return Operation_GET
}

func (m *BackupEntry) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *BackupEntry) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type BackupReply struct {
	Status               Status   `protobuf:"varint,1,opt,name=status,proto3,enum=kv.proto.Status" json:"status,omitempty"`
	Version              int32    `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BackupReply) Reset()         { *m = BackupReply{} }
func (m *BackupReply) String() string { return proto.CompactTextString(m) }
func (*BackupReply) ProtoMessage()    {}
func (*BackupReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_65240d19de191688, []int{1}
}

func (m *BackupReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BackupReply.Unmarshal(m, b)
}
func (m *BackupReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BackupReply.Marshal(b, m, deterministic)
}
func (m *BackupReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BackupReply.Merge(m, src)
}
func (m *BackupReply) XXX_Size() int {
	return xxx_messageInfo_BackupReply.Size(m)
}
func (m *BackupReply) XXX_DiscardUnknown() {
	xxx_messageInfo_BackupReply.DiscardUnknown(m)
}

var xxx_messageInfo_BackupReply proto.InternalMessageInfo

func (m *BackupReply) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_OK
}

func (m *BackupReply) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func init() {
	proto.RegisterType((*BackupEntry)(nil), "kv.proto.BackupEntry")
	proto.RegisterType((*BackupReply)(nil), "kv.proto.BackupReply")
}

func init() {
	proto.RegisterFile("backup.proto", fileDescriptor_65240d19de191688)
}

var fileDescriptor_65240d19de191688 = []byte{
	// 213 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x49, 0x4a, 0x4c, 0xce,
	0x2e, 0x2d, 0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0xc8, 0x2e, 0x83, 0xb0, 0xa4, 0x78,
	0x92, 0xf3, 0x73, 0x73, 0xf3, 0xf3, 0x20, 0x3c, 0xa5, 0x28, 0x2e, 0x6e, 0x27, 0xb0, 0x3a, 0xd7,
	0xbc, 0x92, 0xa2, 0x4a, 0x21, 0x65, 0x2e, 0xa6, 0xfc, 0x02, 0x09, 0x46, 0x05, 0x46, 0x0d, 0x3e,
	0x23, 0x61, 0x3d, 0x98, 0x1e, 0x3d, 0xff, 0x82, 0xd4, 0xa2, 0xc4, 0x92, 0xcc, 0xfc, 0xbc, 0x20,
	0xa6, 0xfc, 0x02, 0x21, 0x01, 0x2e, 0xe6, 0xec, 0xd4, 0x4a, 0x09, 0x26, 0x05, 0x46, 0x0d, 0xce,
	0x20, 0x10, 0x53, 0x48, 0x84, 0x8b, 0xb5, 0x2c, 0x31, 0xa7, 0x34, 0x55, 0x82, 0x19, 0x2c, 0x06,
	0xe1, 0x28, 0x05, 0xc2, 0xcc, 0x0e, 0x4a, 0x2d, 0xc8, 0xa9, 0x14, 0xd2, 0xe0, 0x62, 0x2b, 0x2e,
	0x49, 0x2c, 0x29, 0x2d, 0x86, 0x9a, 0x2f, 0x80, 0x30, 0x3f, 0x18, 0x2c, 0x1e, 0x04, 0x95, 0x17,
	0x92, 0xe0, 0x62, 0x2f, 0x4b, 0x2d, 0x2a, 0xce, 0xcc, 0xcf, 0x03, 0x5b, 0xc2, 0x1a, 0x04, 0xe3,
	0x1a, 0xb9, 0x71, 0x71, 0x78, 0x87, 0x41, 0x0c, 0x15, 0xb2, 0xe2, 0x62, 0x83, 0xb2, 0x44, 0x11,
	0x26, 0x21, 0x79, 0x46, 0x0a, 0x43, 0x18, 0xec, 0x0e, 0x25, 0x06, 0x0d, 0x46, 0x27, 0xf6, 0x28,
	0x56, 0xb0, 0x44, 0x12, 0x1b, 0x98, 0x32, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0xe2, 0x03, 0xf7,
	0xd1, 0x2e, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// KVBackupClient is the client API for KVBackup service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type KVBackupClient interface {
	Backup(ctx context.Context, opts ...grpc.CallOption) (KVBackup_BackupClient, error)
}

type kVBackupClient struct {
	cc grpc.ClientConnInterface
}

func NewKVBackupClient(cc grpc.ClientConnInterface) KVBackupClient {
	return &kVBackupClient{cc}
}

func (c *kVBackupClient) Backup(ctx context.Context, opts ...grpc.CallOption) (KVBackup_BackupClient, error) {
	stream, err := c.cc.NewStream(ctx, &_KVBackup_serviceDesc.Streams[0], "/kv.proto.KVBackup/Backup", opts...)
	if err != nil {
		return nil, err
	}
	x := &kVBackupBackupClient{stream}
	return x, nil
}

type KVBackup_BackupClient interface {
	Send(*BackupEntry) error
	CloseAndRecv() (*BackupReply, error)
	grpc.ClientStream
}

type kVBackupBackupClient struct {
	grpc.ClientStream
}

func (x *kVBackupBackupClient) Send(m *BackupEntry) error {
	return x.ClientStream.SendMsg(m)
}

func (x *kVBackupBackupClient) CloseAndRecv() (*BackupReply, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(BackupReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// KVBackupServer is the server API for KVBackup service.
type KVBackupServer interface {
	Backup(KVBackup_BackupServer) error
}

// UnimplementedKVBackupServer can be embedded to have forward compatible implementations.
type UnimplementedKVBackupServer struct {
}

func (*UnimplementedKVBackupServer) Backup(srv KVBackup_BackupServer) error {
	return status.Errorf(codes.Unimplemented, "method Backup not implemented")
}

func RegisterKVBackupServer(s *grpc.Server, srv KVBackupServer) {
	s.RegisterService(&_KVBackup_serviceDesc, srv)
}

func _KVBackup_Backup_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(KVBackupServer).Backup(&kVBackupBackupServer{stream})
}

type KVBackup_BackupServer interface {
	SendAndClose(*BackupReply) error
	Recv() (*BackupEntry, error)
	grpc.ServerStream
}

type kVBackupBackupServer struct {
	grpc.ServerStream
}

func (x *kVBackupBackupServer) SendAndClose(m *BackupReply) error {
	return x.ServerStream.SendMsg(m)
}

func (x *kVBackupBackupServer) Recv() (*BackupEntry, error) {
	m := new(BackupEntry)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _KVBackup_serviceDesc = grpc.ServiceDesc{
	ServiceName: "kv.proto.KVBackup",
	HandlerType: (*KVBackupServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Backup",
			Handler:       _KVBackup_Backup_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "backup.proto",
}
