// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Operation int32

const (
	Operation_GET    Operation = 0
	Operation_PUT    Operation = 1
	Operation_DELETE Operation = 2
)

var Operation_name = map[int32]string{
	0: "GET",
	1: "PUT",
	2: "DELETE",
}

var Operation_value = map[string]int32{
	"GET":    0,
	"PUT":    1,
	"DELETE": 2,
}

func (x Operation) String() string {
	return proto.EnumName(Operation_name, int32(x))
}

func (Operation) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{0}
}

type Status int32

const (
	Status_OK        Status = 0
	Status_ENOENT    Status = 1
	Status_ENOSERVER Status = 2
	Status_EFAILED   Status = 3
)

var Status_name = map[int32]string{
	0: "OK",
	1: "ENOENT",
	2: "ENOSERVER",
	3: "EFAILED",
}

var Status_value = map[string]int32{
	"OK":        0,
	"ENOENT":    1,
	"ENOSERVER": 2,
	"EFAILED":   3,
}

func (x Status) String() string {
	return proto.EnumName(Status_name, int32(x))
}

func (Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{1}
}

type Key struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Key) Reset()         { *m = Key{} }
func (m *Key) String() string { return proto.CompactTextString(m) }
func (*Key) ProtoMessage()    {}
func (*Key) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{0}
}

func (m *Key) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Key.Unmarshal(m, b)
}
func (m *Key) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Key.Marshal(b, m, deterministic)
}
func (m *Key) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Key.Merge(m, src)
}
func (m *Key) XXX_Size() int {
	return xxx_messageInfo_Key.Size(m)
}
func (m *Key) XXX_DiscardUnknown() {
	xxx_messageInfo_Key.DiscardUnknown(m)
}

var xxx_messageInfo_Key proto.InternalMessageInfo

func (m *Key) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type Value struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Value) Reset()         { *m = Value{} }
func (m *Value) String() string { return proto.CompactTextString(m) }
func (*Value) ProtoMessage()    {}
func (*Value) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{1}
}

func (m *Value) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Value.Unmarshal(m, b)
}
func (m *Value) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Value.Marshal(b, m, deterministic)
}
func (m *Value) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Value.Merge(m, src)
}
func (m *Value) XXX_Size() int {
	return xxx_messageInfo_Value.Size(m)
}
func (m *Value) XXX_DiscardUnknown() {
	xxx_messageInfo_Value.DiscardUnknown(m)
}

var xxx_messageInfo_Value proto.InternalMessageInfo

func (m *Value) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type KVPair struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KVPair) Reset()         { *m = KVPair{} }
func (m *KVPair) String() string { return proto.CompactTextString(m) }
func (*KVPair) ProtoMessage()    {}
func (*KVPair) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{2}
}

func (m *KVPair) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KVPair.Unmarshal(m, b)
}
func (m *KVPair) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KVPair.Marshal(b, m, deterministic)
}
func (m *KVPair) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KVPair.Merge(m, src)
}
func (m *KVPair) XXX_Size() int {
	return xxx_messageInfo_KVPair.Size(m)
}
func (m *KVPair) XXX_DiscardUnknown() {
	xxx_messageInfo_KVPair.DiscardUnknown(m)
}

var xxx_messageInfo_KVPair proto.InternalMessageInfo

func (m *KVPair) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *KVPair) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type WorkerId struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WorkerId) Reset()         { *m = WorkerId{} }
func (m *WorkerId) String() string { return proto.CompactTextString(m) }
func (*WorkerId) ProtoMessage()    {}
func (*WorkerId) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{3}
}

func (m *WorkerId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WorkerId.Unmarshal(m, b)
}
func (m *WorkerId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WorkerId.Marshal(b, m, deterministic)
}
func (m *WorkerId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WorkerId.Merge(m, src)
}
func (m *WorkerId) XXX_Size() int {
	return xxx_messageInfo_WorkerId.Size(m)
}
func (m *WorkerId) XXX_DiscardUnknown() {
	xxx_messageInfo_WorkerId.DiscardUnknown(m)
}

var xxx_messageInfo_WorkerId proto.InternalMessageInfo

func (m *WorkerId) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func init() {
	proto.RegisterEnum("kv.proto.Operation", Operation_name, Operation_value)
	proto.RegisterEnum("kv.proto.Status", Status_name, Status_value)
	proto.RegisterType((*Key)(nil), "kv.proto.Key")
	proto.RegisterType((*Value)(nil), "kv.proto.Value")
	proto.RegisterType((*KVPair)(nil), "kv.proto.KVPair")
	proto.RegisterType((*WorkerId)(nil), "kv.proto.WorkerId")
}

func init() {
	proto.RegisterFile("common.proto", fileDescriptor_555bd8c177793206)
}

var fileDescriptor_555bd8c177793206 = []byte{
	// 231 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x8f, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x46, 0x9b, 0x0d, 0xd9, 0x34, 0x9f, 0x56, 0x96, 0x41, 0x50, 0x04, 0x41, 0x72, 0xd2, 0x1e,
	0x44, 0xf0, 0xe2, 0x55, 0xe9, 0x28, 0x25, 0x25, 0x29, 0x69, 0x8c, 0xe0, 0x2d, 0x9a, 0x3d, 0x84,
	0xd8, 0x6e, 0x59, 0xd3, 0x42, 0xff, 0xbd, 0x6c, 0x2a, 0x28, 0xf4, 0x34, 0x6f, 0x78, 0xf3, 0x0e,
	0x83, 0xe3, 0x4f, 0xb3, 0x5c, 0x9a, 0xd5, 0xed, 0xda, 0x9a, 0xce, 0xd0, 0xb0, 0xdd, 0xee, 0x29,
	0x3e, 0x83, 0x9f, 0xe8, 0x1d, 0x29, 0xf8, 0xad, 0xde, 0x9d, 0x7b, 0x57, 0xde, 0x75, 0x94, 0x3b,
	0x8c, 0x2f, 0x11, 0x94, 0xd5, 0xd7, 0x46, 0xd3, 0x29, 0x82, 0xad, 0x83, 0x5f, 0xb9, 0x5f, 0xe2,
	0x3b, 0xc8, 0xa4, 0x9c, 0x57, 0x8d, 0x3d, 0x4c, 0xff, 0x0a, 0xf1, 0xbf, 0xb8, 0xc0, 0xf0, 0xcd,
	0xd8, 0x56, 0xdb, 0x69, 0x4d, 0x27, 0x10, 0x4d, 0xdd, 0x27, 0xa3, 0x5c, 0x34, 0xf5, 0xf8, 0x06,
	0x51, 0xb6, 0xd6, 0xb6, 0xea, 0x1a, 0xb3, 0xa2, 0x10, 0xfe, 0x0b, 0x17, 0x6a, 0xe0, 0x60, 0xfe,
	0x5a, 0x28, 0x8f, 0x00, 0x39, 0xe1, 0x19, 0x17, 0xac, 0xc4, 0xf8, 0x01, 0x72, 0xd1, 0x55, 0xdd,
	0xe6, 0x9b, 0x24, 0x44, 0x96, 0xa8, 0x81, 0xb3, 0x9c, 0x66, 0x9c, 0xba, 0xcb, 0x11, 0x22, 0x4e,
	0xb3, 0x05, 0xe7, 0x25, 0xe7, 0x4a, 0xd0, 0x11, 0x42, 0x7e, 0x7e, 0x9c, 0xce, 0x78, 0xa2, 0xfc,
	0xa7, 0xf0, 0x3d, 0xe8, 0x7f, 0xfe, 0x90, 0xfd, 0xb8, 0xff, 0x09, 0x00, 0x00, 0xff, 0xff, 0xb2,
	0x8c, 0x1a, 0x0b, 0x14, 0x01, 0x00, 0x00,
}
