// Code generated by protoc-gen-go. DO NOT EDIT.
// source: master.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetWorkerResponse struct {
	Status               Status   `protobuf:"varint,1,opt,name=status,proto3,enum=kv.proto.Status" json:"status,omitempty"`
	Worker               *Worker  `protobuf:"bytes,2,opt,name=worker,proto3" json:"worker,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetWorkerResponse) Reset()         { *m = GetWorkerResponse{} }
func (m *GetWorkerResponse) String() string { return proto.CompactTextString(m) }
func (*GetWorkerResponse) ProtoMessage()    {}
func (*GetWorkerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9c348dec43a6705, []int{0}
}

func (m *GetWorkerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetWorkerResponse.Unmarshal(m, b)
}
func (m *GetWorkerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetWorkerResponse.Marshal(b, m, deterministic)
}
func (m *GetWorkerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetWorkerResponse.Merge(m, src)
}
func (m *GetWorkerResponse) XXX_Size() int {
	return xxx_messageInfo_GetWorkerResponse.Size(m)
}
func (m *GetWorkerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetWorkerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetWorkerResponse proto.InternalMessageInfo

func (m *GetWorkerResponse) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_OK
}

func (m *GetWorkerResponse) GetWorker() *Worker {
	if m != nil {
		return m.Worker
	}
	return nil
}

type Worker struct {
	Hostname             string   `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Port                 int32    `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Worker) Reset()         { *m = Worker{} }
func (m *Worker) String() string { return proto.CompactTextString(m) }
func (*Worker) ProtoMessage()    {}
func (*Worker) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9c348dec43a6705, []int{1}
}

func (m *Worker) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Worker.Unmarshal(m, b)
}
func (m *Worker) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Worker.Marshal(b, m, deterministic)
}
func (m *Worker) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Worker.Merge(m, src)
}
func (m *Worker) XXX_Size() int {
	return xxx_messageInfo_Worker.Size(m)
}
func (m *Worker) XXX_DiscardUnknown() {
	xxx_messageInfo_Worker.DiscardUnknown(m)
}

var xxx_messageInfo_Worker proto.InternalMessageInfo

func (m *Worker) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *Worker) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func init() {
	proto.RegisterType((*GetWorkerResponse)(nil), "kv.proto.GetWorkerResponse")
	proto.RegisterType((*Worker)(nil), "kv.proto.Worker")
}

func init() {
	proto.RegisterFile("master.proto", fileDescriptor_f9c348dec43a6705)
}

var fileDescriptor_f9c348dec43a6705 = []byte{
	// 203 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xc9, 0x4d, 0x2c, 0x2e,
	0x49, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0xc8, 0x2e, 0x83, 0xb0, 0xa4, 0x78,
	0x92, 0xf3, 0x73, 0x73, 0xf3, 0xf3, 0x20, 0x3c, 0xa5, 0x74, 0x2e, 0x41, 0xf7, 0xd4, 0x92, 0xf0,
	0xfc, 0xa2, 0xec, 0xd4, 0xa2, 0xa0, 0xd4, 0xe2, 0x82, 0xfc, 0xbc, 0xe2, 0x54, 0x21, 0x0d, 0x2e,
	0xb6, 0xe2, 0x92, 0xc4, 0x92, 0xd2, 0x62, 0x09, 0x46, 0x05, 0x46, 0x0d, 0x3e, 0x23, 0x01, 0x3d,
	0x98, 0x6e, 0xbd, 0x60, 0xb0, 0x78, 0x10, 0x54, 0x1e, 0xa4, 0xb2, 0x1c, 0xac, 0x57, 0x82, 0x49,
	0x81, 0x51, 0x83, 0x1b, 0x59, 0x25, 0xd4, 0x4c, 0xa8, 0xbc, 0x92, 0x05, 0x17, 0x1b, 0x44, 0x44,
	0x48, 0x8a, 0x8b, 0x23, 0x23, 0xbf, 0xb8, 0x24, 0x2f, 0x31, 0x37, 0x15, 0x6c, 0x3e, 0x67, 0x10,
	0x9c, 0x2f, 0x24, 0xc4, 0xc5, 0x52, 0x90, 0x5f, 0x54, 0x02, 0x36, 0x8d, 0x35, 0x08, 0xcc, 0x36,
	0xf2, 0xe2, 0xe2, 0xf0, 0x0e, 0xf3, 0x05, 0x7b, 0x46, 0xc8, 0x8e, 0x8b, 0x0f, 0xee, 0x5c, 0xa7,
	0x4a, 0xef, 0xd4, 0x4a, 0x21, 0x5e, 0x84, 0x8d, 0xde, 0xa9, 0x95, 0x52, 0xd2, 0x08, 0x2e, 0x86,
	0xbf, 0x94, 0x18, 0x9c, 0xd8, 0xa3, 0x58, 0xc1, 0x92, 0x49, 0x6c, 0x60, 0xca, 0x18, 0x10, 0x00,
	0x00, 0xff, 0xff, 0x84, 0xf7, 0x31, 0xc1, 0x26, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// KVMasterClient is the client API for KVMaster service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type KVMasterClient interface {
	GetWorkerByKey(ctx context.Context, in *Key, opts ...grpc.CallOption) (*GetWorkerResponse, error)
}

type kVMasterClient struct {
	cc grpc.ClientConnInterface
}

func NewKVMasterClient(cc grpc.ClientConnInterface) KVMasterClient {
	return &kVMasterClient{cc}
}

func (c *kVMasterClient) GetWorkerByKey(ctx context.Context, in *Key, opts ...grpc.CallOption) (*GetWorkerResponse, error) {
	out := new(GetWorkerResponse)
	err := c.cc.Invoke(ctx, "/kv.proto.KVMaster/GetWorkerByKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KVMasterServer is the server API for KVMaster service.
type KVMasterServer interface {
	GetWorkerByKey(context.Context, *Key) (*GetWorkerResponse, error)
}

// UnimplementedKVMasterServer can be embedded to have forward compatible implementations.
type UnimplementedKVMasterServer struct {
}

func (*UnimplementedKVMasterServer) GetWorkerByKey(ctx context.Context, req *Key) (*GetWorkerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWorkerByKey not implemented")
}

func RegisterKVMasterServer(s *grpc.Server, srv KVMasterServer) {
	s.RegisterService(&_KVMaster_serviceDesc, srv)
}

func _KVMaster_GetWorkerByKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Key)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KVMasterServer).GetWorkerByKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kv.proto.KVMaster/GetWorkerByKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KVMasterServer).GetWorkerByKey(ctx, req.(*Key))
	}
	return interceptor(ctx, in, info, handler)
}

var _KVMaster_serviceDesc = grpc.ServiceDesc{
	ServiceName: "kv.proto.KVMaster",
	HandlerType: (*KVMasterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetWorkerByKey",
			Handler:    _KVMaster_GetWorkerByKey_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "master.proto",
}
