// Code generated by protoc-gen-go. DO NOT EDIT.
// source: master.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetBackupMastersResponse struct {
	Hostname             string   `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Port                 int32    `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBackupMastersResponse) Reset()         { *m = GetBackupMastersResponse{} }
func (m *GetBackupMastersResponse) String() string { return proto.CompactTextString(m) }
func (*GetBackupMastersResponse) ProtoMessage()    {}
func (*GetBackupMastersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9c348dec43a6705, []int{0}
}

func (m *GetBackupMastersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBackupMastersResponse.Unmarshal(m, b)
}
func (m *GetBackupMastersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBackupMastersResponse.Marshal(b, m, deterministic)
}
func (m *GetBackupMastersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBackupMastersResponse.Merge(m, src)
}
func (m *GetBackupMastersResponse) XXX_Size() int {
	return xxx_messageInfo_GetBackupMastersResponse.Size(m)
}
func (m *GetBackupMastersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBackupMastersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetBackupMastersResponse proto.InternalMessageInfo

func (m *GetBackupMastersResponse) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *GetBackupMastersResponse) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

type GetSlotsResponse struct {
	Version              uint32      `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	SlotTable            []*WorkerId `protobuf:"bytes,2,rep,name=slotTable,proto3" json:"slotTable,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetSlotsResponse) Reset()         { *m = GetSlotsResponse{} }
func (m *GetSlotsResponse) String() string { return proto.CompactTextString(m) }
func (*GetSlotsResponse) ProtoMessage()    {}
func (*GetSlotsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9c348dec43a6705, []int{1}
}

func (m *GetSlotsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSlotsResponse.Unmarshal(m, b)
}
func (m *GetSlotsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSlotsResponse.Marshal(b, m, deterministic)
}
func (m *GetSlotsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSlotsResponse.Merge(m, src)
}
func (m *GetSlotsResponse) XXX_Size() int {
	return xxx_messageInfo_GetSlotsResponse.Size(m)
}
func (m *GetSlotsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSlotsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetSlotsResponse proto.InternalMessageInfo

func (m *GetSlotsResponse) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *GetSlotsResponse) GetSlotTable() []*WorkerId {
	if m != nil {
		return m.SlotTable
	}
	return nil
}

type GetWorkerResponse struct {
	Status               Status   `protobuf:"varint,1,opt,name=status,proto3,enum=kv.proto.Status" json:"status,omitempty"`
	Worker               *Worker  `protobuf:"bytes,2,opt,name=worker,proto3" json:"worker,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetWorkerResponse) Reset()         { *m = GetWorkerResponse{} }
func (m *GetWorkerResponse) String() string { return proto.CompactTextString(m) }
func (*GetWorkerResponse) ProtoMessage()    {}
func (*GetWorkerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9c348dec43a6705, []int{2}
}

func (m *GetWorkerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetWorkerResponse.Unmarshal(m, b)
}
func (m *GetWorkerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetWorkerResponse.Marshal(b, m, deterministic)
}
func (m *GetWorkerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetWorkerResponse.Merge(m, src)
}
func (m *GetWorkerResponse) XXX_Size() int {
	return xxx_messageInfo_GetWorkerResponse.Size(m)
}
func (m *GetWorkerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetWorkerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetWorkerResponse proto.InternalMessageInfo

func (m *GetWorkerResponse) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_OK
}

func (m *GetWorkerResponse) GetWorker() *Worker {
	if m != nil {
		return m.Worker
	}
	return nil
}

type Worker struct {
	Hostname             string   `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Port                 int32    `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Worker) Reset()         { *m = Worker{} }
func (m *Worker) String() string { return proto.CompactTextString(m) }
func (*Worker) ProtoMessage()    {}
func (*Worker) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9c348dec43a6705, []int{3}
}

func (m *Worker) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Worker.Unmarshal(m, b)
}
func (m *Worker) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Worker.Marshal(b, m, deterministic)
}
func (m *Worker) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Worker.Merge(m, src)
}
func (m *Worker) XXX_Size() int {
	return xxx_messageInfo_Worker.Size(m)
}
func (m *Worker) XXX_DiscardUnknown() {
	xxx_messageInfo_Worker.DiscardUnknown(m)
}

var xxx_messageInfo_Worker proto.InternalMessageInfo

func (m *Worker) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *Worker) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func init() {
	proto.RegisterType((*GetBackupMastersResponse)(nil), "kv.proto.GetBackupMastersResponse")
	proto.RegisterType((*GetSlotsResponse)(nil), "kv.proto.GetSlotsResponse")
	proto.RegisterType((*GetWorkerResponse)(nil), "kv.proto.GetWorkerResponse")
	proto.RegisterType((*Worker)(nil), "kv.proto.Worker")
}

func init() {
	proto.RegisterFile("master.proto", fileDescriptor_f9c348dec43a6705)
}

var fileDescriptor_f9c348dec43a6705 = []byte{
	// 335 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x91, 0x41, 0x4f, 0xc2, 0x30,
	0x14, 0xc7, 0x19, 0x2a, 0x8c, 0x07, 0x18, 0xec, 0xc1, 0x2c, 0xe3, 0x42, 0x7a, 0xda, 0xa9, 0x18,
	0xbc, 0x98, 0x78, 0x31, 0x4b, 0x0c, 0x41, 0x63, 0x62, 0x86, 0xd1, 0xc4, 0x83, 0xc9, 0x80, 0x8a,
	0x86, 0x6d, 0x6f, 0x59, 0x1f, 0x18, 0xbe, 0xae, 0x9f, 0xc4, 0xd0, 0x6e, 0xcc, 0x25, 0x72, 0xf0,
	0xb4, 0xbe, 0xbe, 0xb7, 0x5f, 0xdb, 0xdf, 0x1f, 0x3a, 0x71, 0xa8, 0x48, 0x66, 0x22, 0xcd, 0x90,
	0x90, 0xd9, 0xab, 0x8d, 0x59, 0xb9, 0x9d, 0x39, 0xc6, 0x31, 0x26, 0x79, 0xd5, 0x5f, 0x22, 0x2e,
	0x23, 0x39, 0xd4, 0xd5, 0x6c, 0xfd, 0x3e, 0x94, 0x71, 0x4a, 0x5b, 0xd3, 0xe4, 0x77, 0xe0, 0x8c,
	0x25, 0xf9, 0xe1, 0x7c, 0xb5, 0x4e, 0x1f, 0x34, 0x4d, 0x05, 0x52, 0xa5, 0x98, 0x28, 0xc9, 0x5c,
	0xb0, 0x3f, 0x50, 0x51, 0x12, 0xc6, 0xd2, 0xb1, 0x06, 0x96, 0xd7, 0x0a, 0xf6, 0x35, 0x63, 0x70,
	0x9c, 0x62, 0x46, 0x4e, 0x7d, 0x60, 0x79, 0x27, 0x81, 0x5e, 0xf3, 0x37, 0xe8, 0x8d, 0x25, 0x4d,
	0x23, 0xa4, 0x92, 0xe1, 0x40, 0x73, 0x23, 0x33, 0xf5, 0x89, 0x89, 0x46, 0x74, 0x83, 0xa2, 0x64,
	0x17, 0xd0, 0x52, 0x11, 0xd2, 0x53, 0x38, 0x8b, 0xa4, 0x53, 0x1f, 0x1c, 0x79, 0xed, 0x11, 0x13,
	0xc5, 0x13, 0xc4, 0x0b, 0x66, 0x2b, 0x99, 0x4d, 0x16, 0x41, 0x39, 0xc4, 0x97, 0x70, 0x36, 0x96,
	0x64, 0x3a, 0xfb, 0x03, 0x3c, 0x68, 0x28, 0x0a, 0x69, 0xad, 0x34, 0xff, 0x74, 0xd4, 0x2b, 0x19,
	0x53, 0xbd, 0x1f, 0xe4, 0xfd, 0xdd, 0xe4, 0x97, 0xfe, 0x57, 0x5f, 0xba, 0xfd, 0x7b, 0x32, 0x67,
	0xe6, 0x7d, 0x7e, 0x05, 0x0d, 0xb3, 0xf3, 0x5f, 0x05, 0xa3, 0x6f, 0x0b, 0xec, 0xfb, 0x67, 0x23,
	0x92, 0x3d, 0x6a, 0x1f, 0x15, 0xb7, 0xec, 0x5c, 0x98, 0x34, 0x44, 0x91, 0x86, 0xb8, 0xdd, 0xa5,
	0xe1, 0xf2, 0xf2, 0x32, 0x87, 0xf2, 0xe0, 0x35, 0x76, 0x03, 0x76, 0x61, 0xf8, 0x20, 0xc9, 0xad,
	0x90, 0x2a, 0x69, 0xf0, 0x1a, 0xf3, 0xa1, 0xbb, 0x77, 0xe8, 0x6f, 0x27, 0x0b, 0xf6, 0x87, 0x73,
	0xb7, 0x5f, 0x41, 0x54, 0x85, 0xf3, 0x9a, 0xdf, 0x7a, 0x6d, 0x8a, 0x6b, 0x73, 0x6a, 0x43, 0x7f,
	0x2e, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0xa0, 0xd7, 0x40, 0x49, 0x8a, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// KVMasterClient is the client API for KVMaster service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type KVMasterClient interface {
	GetBackupMasters(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GetBackupMastersResponse, error)
	GetSlots(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GetSlotsResponse, error)
	GetWorkerById(ctx context.Context, in *WorkerId, opts ...grpc.CallOption) (*GetWorkerResponse, error)
}

type kVMasterClient struct {
	cc grpc.ClientConnInterface
}

func NewKVMasterClient(cc grpc.ClientConnInterface) KVMasterClient {
	return &kVMasterClient{cc}
}

func (c *kVMasterClient) GetBackupMasters(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GetBackupMastersResponse, error) {
	out := new(GetBackupMastersResponse)
	err := c.cc.Invoke(ctx, "/kv.proto.KVMaster/GetBackupMasters", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kVMasterClient) GetSlots(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GetSlotsResponse, error) {
	out := new(GetSlotsResponse)
	err := c.cc.Invoke(ctx, "/kv.proto.KVMaster/GetSlots", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kVMasterClient) GetWorkerById(ctx context.Context, in *WorkerId, opts ...grpc.CallOption) (*GetWorkerResponse, error) {
	out := new(GetWorkerResponse)
	err := c.cc.Invoke(ctx, "/kv.proto.KVMaster/GetWorkerById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KVMasterServer is the server API for KVMaster service.
type KVMasterServer interface {
	GetBackupMasters(context.Context, *empty.Empty) (*GetBackupMastersResponse, error)
	GetSlots(context.Context, *empty.Empty) (*GetSlotsResponse, error)
	GetWorkerById(context.Context, *WorkerId) (*GetWorkerResponse, error)
}

// UnimplementedKVMasterServer can be embedded to have forward compatible implementations.
type UnimplementedKVMasterServer struct {
}

func (*UnimplementedKVMasterServer) GetBackupMasters(ctx context.Context, req *empty.Empty) (*GetBackupMastersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBackupMasters not implemented")
}
func (*UnimplementedKVMasterServer) GetSlots(ctx context.Context, req *empty.Empty) (*GetSlotsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSlots not implemented")
}
func (*UnimplementedKVMasterServer) GetWorkerById(ctx context.Context, req *WorkerId) (*GetWorkerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWorkerById not implemented")
}

func RegisterKVMasterServer(s *grpc.Server, srv KVMasterServer) {
	s.RegisterService(&_KVMaster_serviceDesc, srv)
}

func _KVMaster_GetBackupMasters_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KVMasterServer).GetBackupMasters(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kv.proto.KVMaster/GetBackupMasters",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KVMasterServer).GetBackupMasters(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _KVMaster_GetSlots_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KVMasterServer).GetSlots(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kv.proto.KVMaster/GetSlots",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KVMasterServer).GetSlots(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _KVMaster_GetWorkerById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkerId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KVMasterServer).GetWorkerById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kv.proto.KVMaster/GetWorkerById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KVMasterServer).GetWorkerById(ctx, req.(*WorkerId))
	}
	return interceptor(ctx, in, info, handler)
}

var _KVMaster_serviceDesc = grpc.ServiceDesc{
	ServiceName: "kv.proto.KVMaster",
	HandlerType: (*KVMasterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBackupMasters",
			Handler:    _KVMaster_GetBackupMasters_Handler,
		},
		{
			MethodName: "GetSlots",
			Handler:    _KVMaster_GetSlots_Handler,
		},
		{
			MethodName: "GetWorkerById",
			Handler:    _KVMaster_GetWorkerById_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "master.proto",
}
